### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by samskiter** [gextech/raml2code-retrofit#2]
Running this through gradle. Tried with several versions of node, keep getting the following error:

```
:servergenerator:gulp_dtos
[...]/node_modules/raml2code-retrofit/lib/tmpl/retrofitClient.hbs:1
unction (exports, require, module, __filename, __dirname) { package {{extra.pa
                                                                    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:69:16)
    at Module._compile (module.js:432:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> ([...]/node_modules/raml2code-retrofit/lib/retrofit-client/index.js:14:19)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

Seems it's trying to compile the template file.

**Comment by domix** [comment]
thanks for using `raml2code-retrofit`, we'll see how to solve your issue.

**Comment by samskiter** [comment]
Thanks @domix I have some time to play with it today so I'll let you know if anything crops up. I've since tried removing gradle from the equation and using "gulp dtos" directly from the command line but get the same error. I can build raml2code-example.

**Comment by samskiter** [comment]
Right, I have a little information. I've slowly worked through the differences between the example project and what I had, turns out I needed the following line in the gulpfile:

```
var genPojos = require("raml2code-groovy-pojo");
```

Which I had omitted as I didn't think I needed that generator.

After I get this running, would you like me to submit a PR to add a little more information to the readme to get this running with a gradle setup?

**Comment by atomsfat** [comment]
Hi, are you using github.com/atomsfat/raml2code-example ?

**Comment by samskiter** [comment]
I tried it out and i can build raml2code-example just fine.

For my gradle project, I followed the instructions on the raml2code readme, which has a gulpfile like so:

``` js
var gulp = require('gulp');
var raml2code = require('raml2code');
//Install a generators:
var genDTO = require("raml2code-retrofit");

gulp.task("dtos", function(){
  gulp.src('./test/cats.raml')
    .pipe(raml2code({generator: genDTO, extra: {package:'com.gex'}}))
    .pipe(gulp.dest('build'));
});
```

changing to this seems to work:

``` js
var gulp = require('gulp');
var raml2code = require('raml2code');
//Install a generators:
var genPojos = require("raml2code-groovy-pojo");
var genDTO = require("raml2code-retrofit");

gulp.task("dtos", function(){
  gulp.src('./test/cats.raml')
    .pipe(raml2code({generator: genDTO, extra: {package:'com.gex'}}))
    .pipe(gulp.dest('build'));
});
```

**Comment by atomsfat** [comment]
Oh you are right, updating the Readme now 

https://github.com/gextech/raml2code/commit/918cad3a112c3e46ffd03c823819aef3bf98edab
